# Thermostat - Living Room
# -- DIYLESS Thermostat 3
# -- https://diyless.com/product/opentherm-thermostat3

# ==================== #
#     BASIC CONFIG     #
# ==================== #
esphome:
  name: diyless-thermostat-living-room
  friendly_name: Thermostat Living Room

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  logs:
    # Reduce verbosity for components that might log sensitive data
    wifi: WARN
    api: WARN

# Enable Home Assistant API
api:
  encryption:
    key: !secret diyless-therm_lr_api-key

# Enable Over-The-Air (OTA) platform to remotely install modified/updated firmware
ota:
  - platform: esphome
    password: !secret diyless-therm_lr_ota-password

# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret network_domain

  # Set minimum WiFi security - reject connections to networks with weaker security
  #min_auth_mode: WPA3
    
# ===================== #
#     SENSOR CONFIG     #
# ===================== #

# i2C pin configuration
i2c:
  sda: GPIO17
  scl: GPIO18
  scan: true

# AHT20 sensor configuration for temperature and humidity
sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature"
      id: builtin_temp
    humidity:
      name: "Humidity"
      id: builtin_hum
    update_interval: 60s
