# Thermostat
# -- DIYLESS Thermostat 3
# -- https://diyless.com/product/opentherm-thermostat3
#
# Board:        DIYLESS THERMOSTAT v3.3 (or v3.2 dependig if you are looking on the back or front of the board)
# Controller:   ESP32-S3-WROOM-1
# Display:      4.0" IPS 480x480 powered by the Sitronix ST7701S display controller
# Touch Panel:  Goodix GT911 touch controller
# Sensor:       AHT20

# =================== #
#     CORE CONFIG     #
# =================== #
substitutions:
  device_name: diyless-thermostat
  friendly_name: Thermostat
  device_description: DIYLESS Thermostat 3 (esp32 with OpenTherm and 4.0-inch display)

# ESPHome Core
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

# ESP32 Platform
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "240"

# Enable logging
logger:
  level: INFO
  logs:
    wifi: WARN
    api: WARN

# ==== CONNECTIVITY ====
# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret network_domain

  min_auth_mode: WPA3

# Enable Home Assistant API
api:
  encryption:
    key: !secret diyless-thermostat__encryption_key

# Enable Over-The-Air (OTA) platform to remotely install modified/updated firmware
ota:
  - platform: esphome
    encryption:

# =================== #
#     COMPONTENTS     #
# =================== #
# ==== INTERFACES AND BUSSES ====
# Enable PSRAM
psram:
  mode: octal
  speed: 80MHz

# Shared I2C Bus [GT911, AHT20]
i2c:
  id: bus_i2c
  sda: GPIO17
  scl: GPIO18
  scan: true

# Shared SPI Bus [ST7701S]
spi:
  id: bus_spi
  clk_pin: GPIO12
  mosi_pin:  GPIO11

# ==== HARDWARE ====
time:
  - id: time_ha
    platform: homeassistant

sensor:
  # AHT20 sensor configuration for temperature and humidity
  - id: sens_builtin
    platform: aht10
    variant: AHT20
    temperature:
      id: sens_builtin_temp
      name: Temperature
      icon: "mdi:thermometer"
    humidity:
      id: sens_builtin_hum
      name: Humidity
      icon: "mdi:water-percent"
    update_interval: 60s

number:
  - id: num_backlight_timeout
    platform: template
    name: Backlight timeout
    icon: mdi:timer-outline
    entity_category: "config"
    optimistic: true
    unit_of_measurement: "s"
    restore_value: true
    initial_value: 60
    min_value: 10
    max_value: 360
    step: 10
    mode: slider

touchscreen:
  - id: touch_main
    platform: gt911
    interrupt_pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
    calibration:
      x_min: 0
      x_max: 480
      y_min: 0
      y_max: 480
    update_interval: 50ms
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log:
                level: DEBUG
                format: "Touch detected: Restoring backlight"
            - light.turn_on: light_backlight

light:
  # RGB display backlight
  - id: light_backlight
    platform: monochromatic
    name: Backlight
    output: out_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    on_turn_on:
      - logger.log:
          level: DEBUG
          format: "Screen on detected: Resuming LVGL engine"
      - lvgl.resume:
      - lvgl.widget.redraw:
    on_turn_off:
      - logger.log:
          level: DEBUG
          format: "Screen off detected: Pause LVGL engine"
      - lvgl.pause:

display:
  - id: disp_main
    platform: mipi_rgb
    model: ST7701S
    dimensions:
      width: 480
      height: 480

    # Display Engine & Color Properties
    color_order: RGB
    invert_colors: true
    pixel_mode: 18bit
    auto_clear_enabled: false
    update_interval: never

    # Clock & Signal Timings
    pclk_frequency: 10MHz
    pclk_inverted: false

    hsync_pulse_width: 14
    hsync_back_porch: 14
    hsync_front_porch: 14

    vsync_pulse_width: 10
    vsync_back_porch: 14
    vsync_front_porch: 14

    # Control Interface Pins
    cs_pin: GPIO1
    reset_pin: GPIO43
    de_pin:
      number: GPIO45
      ignore_strapping_warning: true
    hsync_pin: GPIO5
    vsync_pin: GPIO4
    pclk_pin: GPIO21

    # Parallel RGB Data Bus (5-6-5 Mapping)
    data_pins:
      red:
        - 39        # r1
        - 40        # r2
        - 41        # r3
        - 42        # r4
        - 2         # r5
      green:
        - 0         # g0
        - 9         # g1
        - 14        # g2
        - 47        # g3
        - 48        # g4
        - 3         # g5
      blue:
        - 6         # b1
        - 7         # b2
        - 15        # b3
        - 16        # b4
        - 8         # b5

lvgl:
  displays: disp_main
  touchscreens: touch_main

  on_idle:
    timeout: !lambda "return (id(num_backlight_timeout).state * 1000);"
    then:
      - logger.log:
          level: DEBUG
          format: "LVGL is idle: Deactivating backlight"
      - light.turn_off: light_backlight

output:
  # RGB display backlight output
  - id: out_backlight
    platform: ledc
    pin:
      number: GPIO46
      ignore_strapping_warning: true
