# Thermostat
# -- DIYLESS Thermostat 3
# -- https://diyless.com/product/opentherm-thermostat3
#
# Board:        DIYLESS THERMOSTAT v3.3 (or v3.2 dependig if you are looking on the back or front of the board)
# Controller:   ESP32-S3-WROOM-1
# Display:      4.0" IPS 480x480 powered by the Sitronix ST7701S display controller
# Touch Panel:  Goodix GT911 touch controller
# Sensor:       AHT20

# =================== #
#     CORE CONFIG     #
# =================== #
substitutions:
  device_name: diyless-thermostat
  friendly_name: Thermostat
  device_description: DIYLESS Thermostat 3 (esp32 with OpenTherm and 4.0-inch display)

# ESPHome Core
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio

# ESP32 Platform
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "240"
  flash_size: 8MB

# Enable logging
logger:
  level: INFO
  logs:
    wifi: WARN
    api: WARN

# ==== CONNECTIVITY ====
# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret network_domain

  min_auth_mode: WPA3

# Enable Home Assistant API
api:
  encryption:
    key: !secret diyless-thermostat__encryption_key

# Enable Over-The-Air (OTA) platform to remotely install modified/updated firmware
ota:
  - platform: esphome
    encryption:

# =================== #
#     COMPONTENTS     #
# =================== #
# ==== INTERFACES AND BUSSES ====
# Enable PSRAM
psram:
  mode: octal
  speed: 80MHz

# Shared I2C Bus [GT911, AHT20]
i2c:
  sda: GPIO17
  scl: GPIO18
  scan: true

# Shared SPI Bus [ST7701S]
spi:
  clk_pin: GPIO12
  mosi_pin:  GPIO11

# ==== HARDWARE ====
sensor:
  # AHT20 sensor configuration for temperature and humidity
  - platform: aht10
    variant: AHT20
    temperature:
      id: builtin_temp
      name: Temperature
      icon: "mdi:thermometer"
    humidity:
      id: builtin_hum
      name: Humidity
      icon: "mdi:water-percent"
    update_interval: 60s

    touchscreen:
      - id: diyless_touchscreen
        platform: gt911
        interrupt_pin:
          number: GPIO10
          mode:
            input: true
            pullup: true
        calibration:
          x_min: 0
          x_max: 480
          y_min: 0
          y_max: 480
        update_interval: 50ms
        on_release:
          - if:
              condition: lvgl.is_paused
              then:
                - lvgl.resume:
                - lvgl.widget.redraw:
                - light.turn_on: backlight

light:
  # RGB display backlight
  - platform: monochromatic
    id: backlight
    name: ${friendly_name} Backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 0s

display:
  - platform: mipi_rgb
    id: diyless_display
    model: ST7701S
    auto_clear_enabled: false
    update_interval: never
    pixel_mode: 18bit
    color_order: RGB
    invert_colors: true
    dimensions:
      width: 480
      height: 480

    # Timing & Sync Control Lines
    de_pin: GPIO45
    hsync_pin: GPIO5
    vsync_pin: GPIO4
    pclk_pin: GPIO21
    reset_pin: GPIO43
    pclk_frequency: 10MHz
    pclk_inverted: false

    hsync_pulse_width: 14
    hsync_back_porch: 14
    hsync_front_porch: 14
    vsync_pulse_width: 10
    vsync_back_porch: 14
    vsync_front_porch: 14

    # 16-Bit RGB565 Data Bus
    data_pins:
      red:
        - 39        # r1
        - 40        # r2
        - 41        # r3
        - 42        # r4
        - 2         # r5
      green:
        - 0         # g0
        - 9         # g1
        - 14        # g2
        - 47        # g3
        - 48        # g4
        - 3         # g5
      blue:
        - 6         # b1
        - 7         # b2
        - 15        # b3
        - 16        # b4
        - 8         # b5

output:
  # RGB display backlight output
  - platform: ledc
    id: backlight_output
    pin: GPIO46
