# Thermostat
# -- DIYLESS Thermostat 3
# -- https://diyless.com/product/opentherm-thermostat3
#
# Board:        DIYLESS THERMOSTAT v3.3 (or v3.2 dependig if you are looking on the back or front of the board)
# Controller:   ESP32-S3-WROOM-1
# Display:      4.0" IPS 480x480 powered by the Sitronix ST7701S display controller
# Touch Panel:  Goodix GT911 touch controller
# Sensor:       AHT20

# ===================== #
#     BASIC CONFIG      #
# ===================== #
substitutions:
  device_name: diyless-thermostat
  friendly_name: Thermostat
  device_description: DIYLESS Thermostat 3 (esp32 with OpenTherm and 4.0-inch display)

# ESPHome Core
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio

# ESP32 Platform
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "240"
  flash_size: 8MB

# Enable logging
logger:
  level: INFO
  logs:
    wifi: WARN
    api: WARN

# ==== CONNECTIVITY ====
# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret network_domain

  min_auth_mode: WPA3

# Enable Home Assistant API
api:
  encryption:
    key: !secret diyless-thermostat__encryption_key

# Enable Over-The-Air (OTA) platform to remotely install modified/updated firmware
ota:
  - platform: esphome
    encryption:

# ===================== #
#     SENSOR CONFIG     #
# ===================== #
# ==== INTERFACES AND BUSSES ====
# Enable PSRAM
psram:
  mode: octal
  speed: 80MHz

# Shared I2C Bus [GT911, AHT20]
i2c:
  sda: GPIO17
  scl: GPIO18
  scan: true

# ==== SENNSORS ====
# AHT20 sensor configuration for temperature and humidity
sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: Temperature
      id: builtin_temp
      icon: "mdi:thermometer"
    humidity:
      name: Humidity
      id: builtin_hum
      icon: "mdi:water-percent"
    update_interval: 60s
